=== pecrom/networkmanager/manager/src/main/resources/cz/pecrom/xsd/menu.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="menu">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="menuItem" type="MenuItem" minOccurs="1" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:complexType name="ApplicationItem">
        <xs:sequence>
            <xs:element type="xs:string" name="label" minOccurs="1" maxOccurs="1"/>
            <xs:element type="xs:string" name="controller" minOccurs="1" maxOccurs="1"/>
            <xs:element type="xs:string" name="view" minOccurs="1" maxOccurs="1"/>
            <xs:element type="xs:string" name="form" minOccurs="1" maxOccurs="1"/>
            <xs:element type="xs:string" name="model" minOccurs="1" maxOccurs="1"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="MenuItem">
        <xs:sequence>
            <xs:element type="xs:string" name="label" minOccurs="1" maxOccurs="1" />
            <xs:element type="MenuItem" name="children" minOccurs="0" maxOccurs="unbounded"/>
            <xs:element type="ApplicationItem" name="application" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
</xs:schema>

=== pecrom/networkmanager/manager/src/main/resources/cz/pecrom/controller/main/DesktopController.xml
<?xml version="1.0" encoding="ISO-8859-1"?>

<menu xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../xsd/menu.xsd">
    <menuItem>
        <label>Applications</label>
        <application>
            <label>Sniffer</label>
            <controller>cz.pecrom.controller.apps.sniffer.SnifferController</controller>
            <view>cz.pecrom.view.apps.sniffer.Sniffer_Form</view>
        </application>               
    </menuItem>  
    <menuItem>
        <label>About</label>
        <application>
            <label>About</label>
            <controller>cz.pecrom.controller.main.AboutController</controller>
            <view>cz.pecrom.view.main.About_Form</view>
        </application>
    </menuItem>
</menu>
